../src/asm 10_ldi_DDR.s
../src/asm 10_ldi_DRR.s
../src/asm 10_ldi_IDR_neg.s
../src/asm 10_ldi_IDR_pos.s
../src/asm 10_ldi_IRR_neg.s
../src/asm 10_ldi_IRR_pos.s
../src/asm 10_ldi_RDR.s
../src/asm 10_ldi_RRR.s
../src/asm 11_sti_RDD.s
../src/asm 11_sti_RDR.s
../src/asm 11_sti_RID.s
../src/asm 11_sti_RIR.s
../src/asm 11_sti_RRD.s
../src/asm 11_sti_RRR.s
../src/asm 12_fork_D.s
../src/asm 13_lld_DR.s
../src/asm 13_lld_IR_neg.s
../src/asm 13_lld_IR_pos.s
../src/asm 14_lldi_DDR.s
../src/asm 14_lldi_DRR.s
../src/asm 14_lldi_IDR_neg.s
../src/asm 14_lldi_IDR_pos.s
../src/asm 14_lldi_IRR_neg.s
../src/asm 14_lldi_IRR_pos.s
../src/asm 14_lldi_RDR.s
../src/asm 14_lldi_RRR.s
../src/asm 15_lfork.s
../src/asm 16_aff_R.s
../src/asm 16_aff_mod256.s
../src/asm 1_live_D.s
../src/asm 2_ld_DR.s
../src/asm 2_ld_IR_neg.s
../src/asm 2_ld_IR_pos.s
../src/asm 3_st_RI.s
../src/asm 3_st_RI_negat.s
../src/asm 3_st_RR.s
../src/asm 4_add_RRR_no_zjmp.s
../src/asm 4_add_RRR_with_zjmp.s
../src/asm 5_sub_RRR_no_zjmp.s
../src/asm 5_sub_RRR_with_zjmp.s
../src/asm 6_and_DDR.s
../src/asm 6_and_DIR.s
../src/asm 6_and_DRR.s
../src/asm 6_and_IDR.s
../src/asm 6_and_IIR.s
../src/asm 6_and_IRR.s
../src/asm 6_and_RDR.s
../src/asm 6_and_RIR.s
../src/asm 6_and_RRR.s
../src/asm 7_or_DDR.s
../src/asm 7_or_DIR.s
../src/asm 7_or_DRR.s
../src/asm 7_or_IDR.s
../src/asm 7_or_IIR.s
../src/asm 7_or_IRR.s
../src/asm 7_or_RDR.s
../src/asm 7_or_RIR.s
../src/asm 7_or_RRR.s
../src/asm 8_xor_DDR.s
../src/asm 8_xor_DIR.s
../src/asm 8_xor_DRR.s
../src/asm 8_xor_IDR.s
../src/asm 8_xor_IIR.s
../src/asm 8_xor_IRR.s
../src/asm 8_xor_RDR.s
../src/asm 8_xor_RIR.s
../src/asm 8_xor_RRR.s
../src/asm 9_zjmp_D.s
../src/asm 9_zjmp_D_neg.s
../src/asm bad_magic.s
../src/asm bad_prog_size.s
../src/asm big_op.s
../src/asm empty_with_zero_op.s
../src/asm empty_without_opcode.s
../src/asm nyatsulk_bot.s
../src/asm overwrite_op.s
../src/asm small_op.s